version: "3.9"
services:
  postgres:
    image: "postgres:16-alpine"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./database/script/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clientapp
    restart: always

  clientapp:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DBNAME: clientapp
      DB_PORT: 5432
      DATABASE_URL: postgresql://postgres:postgres@postgres/clientapp
      TICKET_APP: http://ticketapp:4000
      WAIT_HOSTS: postgres:5432
    # restart: always
volumes:
  postgres:


networks:
  default:
    name: my-network
    external: true
