version: '3.9'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticket
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 2s
      retries: 10

  # mq:
  #   image: webcenter/activemq
  #   restart: always
  #   ports:
  #     - '61616:61616'
  #     - '8161:8161'
  #   healthcheck:
  #     test: [ "NONE" ]

  ticket-mq:
    image: "rabbitmq:3-management"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 10

  ticketapp:
    build: .
    depends_on:
      db:
        condition: service_healthy
      ticket-mq:
        condition: service_healthy
    ports:
      - "4000:4000"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DBNAME: ticket
      DB_PORT: 5432
      DATABASE_URL: postgresql://postgres:postgres@db:5432/ticket?schema=public
      RABBITMQ_HOST: ticket-mq
      WAIT_HOSTS: postgres:5432

networks:
  default:
    name: my-network
    external: true
