version: '3.9'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticket
    volumes:
      - ./data:/var/lib/postgresql/data
  
  mq:
    image: webcenter/activemq
    restart: always
    ports:
      - '61616:61616'
      - '8161:8161'
  
  ticketapp:
    build: .
    depends_on:
      - db
      - mq
    ports:
      - "4000:4000"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DBNAME: ticket
      DB_PORT: 5432
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/ticket?schema=public
      WAIT_HOSTS: postgres:5432