version: '3.9'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticket
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 2s
      retries: 10

  mq:
    image: webcenter/activemq
    restart: always
    ports:
      - '61616:61616'
      - '8161:8161'
    healthcheck:
      test: [ "NONE" ]

  ticketapp:
    build: .
    depends_on:
      db:
        condition: service_healthy
      mq:
        condition: service_started
    ports:
      - "6000:6000"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DBNAME: ticket
      DB_PORT: 5432
      DATABASE_URL: postgresql://postgres:postgres@db:5432/ticket?schema=public
      WAIT_HOSTS: postgres:5432

networks:
  default:
    name: my-network
    external: true
